sudo: required
services:
  - docker

before_install:
  - docker build -t jkolden/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jkolden/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-278001651727"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $aws-access-key
  secret_access_key:
    secure: $aws-secret-key

